import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"

import { useSession, signIn, signOut } from "next-auth/react"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const { data: session } = useSession()
  console.log(session)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>USER SHOULD BE HERE</p>
        {session && (
          <>
            Signed in<br />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        )}

        {!session && (
          <>
            Not signed in <br />
            <button onClick={() => signIn()}>Sign in</button>
          </>
        )}
      </main>
    </>
  )
}
