import Head from "next/head";
import styles from "@/styles/IssueContainer.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Issue from "@/components/issueContainer";
import IssueButtons from "@/components/IssueButtons";
import SearchBar from "@/components/IssueSearchBar";
import { useState } from "react";
import prisma from "@/lib/prisma/prisma";

//added issuesData as a prop
export default function Issues({ issuesData }) {
  console.log(issuesData)
  const [filteredIssues, setFilteredIssues] = useState(issuesData);

  const handleSearch = (searchTerm) => {
    const filtered = issuesData.filter((issue) =>
      issue.labels.some((label) =>
        label.name.toLowerCase().includes(searchTerm.toLowerCase())
      )
    );
    setFilteredIssues(filtered);
  };

  return (
    <>
      <Head>
        <title>Issues list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainContainer}>
        <Header />
        <div className={styles.topContainer}>
          {" "}
          Add a container for the top elements
          <IssueButtons />
        </div>
        <div className={styles.issueListContainer}>
          {filteredIssues.map((issue, index) => (
            <Issue key={index} issue={issue} />
          ))}
        </div>
        <Footer />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const { namespaceName, projectName } = context.query
  const issuesData = await prisma.issue.findMany({
    where: {
      project: {
        name: projectName,
        namespace: {
          name: namespaceName
        }
      }
    },
    include: {
      labels: true
    },
  });

  console.log(issuesData)

  return {
    props: {
      issuesData: issuesData.map((issue) => ({
        ...issue,
        createdAt: issue.createdAt.toISOString(),
        updatedAt: issue.updatedAt.toISOString(),
      })),
    },
  };
}
