import Head from "next/head"
import { useRouter } from "next/router"

import { NamespaceNameCreationSchema } from "@/lib/yup-schemas"
import { Formik, Form, Field } from "formik"

import Header from "@/components/Header"

import axios from "axios"
import ProjectBelowNavbar from "@/components/navbar/ProjectBelowNavbar"

export default function ProjectInvites(props) {
  const router = useRouter()
  const { namespaceName, projectName } = router.query

  return (
    <>
      <Head>
        <title>Invite Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-screen overflow-hidden">
        <div className="relative flex flex-col flex-1 overflow-y-auto overflow-x-hidden">
          <Header />
          <ProjectBelowNavbar
            namespaceName={namespaceName}
            projectName={projectName}
            selected={"invites"}
          />
          <main>
            <div className="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto">
              <div className="mb-8">
                <div className="flex flex-col md:flex-row md:-mr-px">
                  <div className="grow">
                    <div className="p-6 space-y-6">
                      <section>
                        <h2 className="text-3xl leading-snug text-slate-800 font-bold mb-1">
                          Invite a user to join {projectName}
                        </h2>
                        <div className="">
                          <Formik
                            initialValues={{
                              name: ""
                            }}
                            validationSchema={NamespaceNameCreationSchema}
                            onSubmit={(
                              values,
                              { setSubmitting, setFieldError }
                            ) => {
                              axios
                                .post(
                                  `/api/${namespaceName}/${projectName}/invites`,
                                  {
                                    name: values.name,
                                    role: values.role
                                  }
                                )
                                .then((response) => {
                                  console.log("RESPONSE:", response)
                                  // TODO: Redirect to new project page
                                  // router.push("/")
                                })
                                .catch((error) => {
                                  console.log("ERROR:", error.response.data)
                                  console.log("ERROR:", error)
                                })
                                .finally(() => {
                                  setSubmitting(false)
                                })
                            }}
                          >
                            {({ values, errors, isSubmitting }) => (
                              <Form>
                                <section className="flex flex-row mb-4 gap-x-4">
                                  <div className="sm:w-1/3">
                                    <label
                                      className="block text-sm font-medium mb-1"
                                      htmlFor="name"
                                    >
                                      Username{" "}
                                      <span className="text-rose-500">*</span>
                                    </label>
                                    <Field
                                      className="form-input w-full"
                                      type="text"
                                      name="name"
                                    />
                                  </div>

                                  <div className="w-1/6">
                                    <label
                                      className="block text-sm font-medium mb-1"
                                      htmlFor="owner"
                                    >
                                      Role{" "}
                                      <span className="text-rose-500">*</span>
                                    </label>

                                    <Field
                                      className="form-input w-full "
                                      as="select"
                                      name="role"
                                    >
                                      <option value="User">User</option>
                                      <option value="Owner">Owner</option>
                                    </Field>
                                  </div>
                                </section>

                                {errors.name && (
                                  <div>Name errors:{errors.name}</div>
                                )}

                                <hr />

                                <div className="flex flex-col py-5 border-t border-slate-200">
                                  <div className="flex self-start">
                                    <button
                                      className="btn bg-indigo-500 hover:bg-indigo-600 text-white"
                                      type="submit"
                                      disabled={isSubmitting}
                                    >
                                      Invite User
                                    </button>
                                  </div>
                                </div>
                              </Form>
                            )}
                          </Formik>
                        </div>
                      </section>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    </>
  )
}
