import Head from "next/head";
import { Inter } from "next/font/google";
import layoutStyles from "@/styles/usersLayout.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import LabelList from "@/components/LabelList";
import LabelSearchBar from "@/components/LabelSearchBar";

import prisma from "@/lib/prisma/prisma";

export default function LabelPage(props) {

  console.log(props)

  const handleSearch = (searchTerm) => {
    console.log("Searching:", searchTerm);
    // Implement search logic here
  };

  return (
    <>
      <Head>
        <title>Label Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${layoutStyles.main} ${layoutStyles.mainContent}`}>
        <Header />
        <div className={layoutStyles.labelsContainer}>
          <LabelSearchBar onSearch={handleSearch} />
          <LabelList labels={props.labelData} />
        </div>
        <Footer />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const { namespaceName, projectName } = context.query
  const labelData = await prisma.label.findMany({
    where: {
      project: {
        name: projectName,
        namespace: {
          name: namespaceName
        }
      }
    }
  });

  console.log(labelData)

  return {
    props: { labelData }
  };
}
