import Head from "next/head"

import "bootstrap/dist/css/bootstrap.min.css"

export default function OrganizationCreate() {
  return (
    <>
      <Head>
        <title>Create new Organization</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-5" />

      <div className="container">
        <h2>Create a new Organization</h2>

        <hr />

        <form>
          <div className="mb-3">
            <label htmlFor="exampleInputEmail1" className="form-label">
              Organization Name
            </label>
            <input
              type="text"
              className="form-control"
              id="name"
              aria-describedby="nameHelp"
            />
            <div id="name" className="form-text">
              <p>This will be the name of your account on GitHub.</p>
              <p>Your URL will be: https://github.com/[AUTO-FILL-TEXT-HERE]</p>
            </div>
          </div>

          <hr />

          <button type="submit" className="btn btn-success">
            Create Organization
          </button>
        </form>
      </div>
    </>
  )
}
