import { useState } from "react"
import { useRouter } from "next/router"
import Head from "next/head"

import { useSession } from "next-auth/react"
import { setCookie } from "cookies-next"

import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"

import Button from "react-bootstrap/Button"
import Form from "react-bootstrap/Form"

import axios from "axios"
import { NEW_USER_COOKIE } from '@/lib/constants'
const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  const router = useRouter()

  const { data: session } = useSession()
  const [submitting, setSubmitting] = useState(false)
  const [name, setName] = useState("")

  console.log("Session:", session)

  const onSubmit = async (event) => {
    event.preventDefault()

    if (submitting) {
      return
    }

    setSubmitting(true)

    axios
      .post("/api/user", {
        name: name
      })
      .then((response) => {
        console.log("RESPONSE:", response)
        // setCookie(NEW_USER_COOKIE, "", { maxAge: -1 })
        router.push("/")
      })
      .catch((error) => {
        console.log("ERROR:", error.response.data)
        console.log("ERROR:", error)
      })
      .finally(() => {
        setSubmitting(false)
      })
  }

  return (
    <>
      <Head>
        <title>Create namespace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Form onSubmit={onSubmit}>
          <Form.Group className="mb-3" controlId="formBasicEmail">
            <Form.Label className={inter.className}>Username here</Form.Label>
            <br />
            <Form.Control
              type="text"
              placeholder="Enter new username"
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
          </Form.Group>
          <Button variant="primary" type="submit">
            Submit
          </Button>
        </Form>
      </main>
    </>
  )
}
