import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Bug-Zapper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"/>
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/WM6avuye5x+z7gDzFgLp5B45SY8U4h0EK10M5d"
          crossOrigin="anonymous"
        />
      </Head>
      <Header />

      <main className="bg-white min-h-screen">
        <div className="relative md:flex">
          <div className="md:w-1/2">
            {/* Add your left side content here */}
          </div>
          <div className="hidden md:block relative md:w-1/2 image-container">
            <Image
              src="/images/homepic.avif"
              alt="Sign In Page"
              layout="responsive"
              width={1000} // Replace with your desired width
              height={500} // Replace with your desired height
              objectFit="cover"
              objectPosition="center"
            />
          </div>
        </div>
      </main>
    </>
  );
}