import {
  getProviders,
  signIn,
  getSession,
  getCsrfToken,
} from "next-auth/react";
import Head from "next/head";
import Header from "@/components/Header";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faGithub, faGoogle } from "@fortawesome/free-brands-svg-icons";
import { faBug } from "@fortawesome/free-solid-svg-icons";

import Image from 'next/image';

function signin({ providers }) {
  return (
    <>
      <Head>
        <title>Sign In Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style jsx>{`
          .image-container {
            height: calc(100vh - HEADER_HEIGHT - FOOTER_HEIGHT);
          }
          .header, .footer {
            z-index: 10;
          }
        `}</style>
      </Head>
      <main className="bg-slate-100 min-h-screen">
        <Header className="header" />
        <div className="relative md:flex">
          <div className="md:w-1/2">
            <div className="min-h-screen h-full flex flex-col">
              <div className="flex-1 flex justify-center items-center">
                <div className="px-4 sm:px-6 lg:px-8 py-8 max-w-sm mx-auto">
                  <h1 className="text-3xl text-gray-800 font-bold mb-6">Sign In</h1>
                  {Object.values(providers).map((provider) => {
                    const icon = provider.name === "GitHub" ? faGithub : faGoogle;
                    return (
                      <div key={provider.name} className="mb-4">
                        <button
                          className="w-full bg-green-600 hover:bg-green-500 text-white p-2 rounded flex items-center justify-center"
                          onClick={() => signIn(provider.id)}
                        >
                          <FontAwesomeIcon icon={icon} className="mr-2" />
                          Sign in with {provider.name}
                        </button>
                      </div>
                    );
                  })}
                </div>
              </div>
            </div>
          </div>
          <div className="hidden md:block relative md:w-1/2 image-container">
            <Image
              src="/images/signinpage.jpg"
              alt="Sign In Page"
              fill
              style={{
                objectFit: "cover",
                objectPosition: "center",
              }}
            />
          </div>
        </div>
        <div className="fixed inset-x-0 bottom-0 flex justify-center items-center pb-4">
        <div className="text-center">
          <FontAwesomeIcon icon={faBug} />
          <p className="mt-2">Bug-Zapper</p>
        </div>
      </div>
      </main>
    </>
  );
}
export async function getServerSideProps(context) {
  const session = await getSession(context);
  if (session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  const providers = await getProviders();
  const csrfToken = await getCsrfToken(context);

  return {
    props: {
      providers,
      csrfToken,
    },
  };
}

export default signin;

