import Head from "next/head"
import Image from "next/image"
import Header from "@/components/Header"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import {
  faGithub,
  faGoogle,
  faGitlab,
  faMicrosoft,
  faLinkedin
} from "@fortawesome/free-brands-svg-icons"

import { getProviders, signIn, getSession, getCsrfToken } from "next-auth/react"

function SignIn({ providers }) {
  const providerIcons = {
    GitHub: faGithub,
    Google: faGoogle,
    GitLab: faGitlab,
    Microsoft: faMicrosoft,
    LinkedIn: faLinkedin
  }

  return (
    <>
      <Head>
        <title>Sign In Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-slate-100 min-h-screen">
        <Header className="header" />
        <div className="relative md:flex">
          <div className="md:w-1/2">
            <div className="min-h-screen h-full flex flex-col">
              <div className="flex-1 flex justify-center items-center">
                <div className="px-4 sm:px-6 lg:px-8 py-8 max-w-sm mx-auto">
                  <h1 className="text-3xl text-gray-800 text-center font-bold mb-6">
                    Sign In
                  </h1>
                  {Object.values(providers).map((provider) => {
                    const lookupIcon = providerIcons[provider.name]
                    if (lookupIcon) {
                      return (
                        <div key={provider.name} className="mb-4">
                          <button
                            className="w-full bg-white hover:bg-gray-300 text-black p-2 rounded flex items-center justify-center border"
                            onClick={() => signIn(provider.id)}
                          >
                            <FontAwesomeIcon icon={lookupIcon} className="mr-2" />
                            Sign in with {provider.name}
                          </button>
                        </div>
                      )
                    }
                  })}
                </div>
              </div>
            </div>
          </div>
          <div className="hidden md:block relative md:w-1/2 image-container">
            <Image
              src="/images/signinpage.jpg"
              alt="Sign In Page"
              fill
              style={{
                objectFit: "cover",
                objectPosition: "center"
              }}
            />
          </div>
        </div>
      </main>
    </>
  )
}
export async function getServerSideProps(context) {
  const session = await getSession(context)
  if (session) {
    return {
      redirect: {
        destination: "/",
        permanent: false
      }
    }
  }

  const providers = await getProviders()
  const csrfToken = await getCsrfToken(context)

  return {
    props: {
      providers,
      csrfToken
    }
  }
}

export default SignIn
