import Head from "next/head";
import styles from "@/styles/IssueContainer.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import IssueList from "@/components/IssueList"; // Add this import
import IssueButtons from "@/components/IssueButtons";
import SearchBar from "@/components/IssueSearchBar";
import { useState } from "react";
import prisma from "../../lib/prisma/prisma";

export async function getServerSideProps() {
  const issuesData = await prisma.issue.findMany({
    include: {
      labels: true,
    },
  });

  return {
    props: {
      issuesData: issuesData.map((issue) => ({
        ...issue,
        createdAt: issue.createdAt.toISOString(),
        updatedAt: issue.updatedAt.toISOString(),
      })),
    },
  };
}

export default function Issues({ issuesData }) {
  const [filteredIssues, setFilteredIssues] = useState(issuesData);

  const handleSearch = (searchTerm) => {
    const filtered = issuesData.filter((issue) =>
      issue.name.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredIssues(filtered);
  };

  return (
    <>
      <Head>
        {/* ... Head content ... */}
      </Head>
      <main className={styles.mainContainer}>
        <Header />
        <div className={styles.topContainer}>
        <IssueButtons onSearch={handleSearch} /> {/* Pass the handleSearch function */}
        </div>
        <div className={styles.issueListContainer}>
          <IssueList issues={filteredIssues} />
        </div>
        <Footer />
      </main>
    </>
  );
}

// export default function Issues({ issuesData }) {
//   const [filteredIssues, setFilteredIssues] = useState(issuesData);

//   const handleSearch = (searchTerm) => {
//     const filtered = issuesData.filter((issue) =>
//       issue.labels.some((label) =>
//         label.name.toLowerCase().includes(searchTerm.toLowerCase())
//       )
//     );
//     setFilteredIssues(filtered);
//   };

//   return (
//     <>
//       <Head>
//         <title>Issues list</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={styles.mainContainer}>
//         <Header />
//         <div className={styles.topContainer}>
//           <IssueButtons />
//         </div>
//         {/* Replace the div below with the provided code */}
//         <div className={styles.issueListContainer}>
//           <IssueList issues={filteredIssues} />
//         </div>
//         <Footer />
//       </main>
//     </>
//   );
// }
