import Head from "next/head"

import "bootstrap/dist/css/bootstrap.min.css"

export default function ProjectCreate() {
  return (
    <>
      <Head>
        <title>Create new Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-5" />

      <div className="container">
        <h2>Create a new repository</h2>
        <p>
          A repository contains all project files, including the revision
          history. Already have a project repository elsewhere?
        </p>

        <hr />

        <form>
          <div className="mb-3">
            <label htmlFor="exampleInputEmail1" className="form-label">
              Project Name
            </label>
            <input
              type="text"
              className="form-control"
              id="name"
              aria-describedby="nameHelp"
            />
            <div id="name" className="form-text">
              Great repository names are short and memorable.
            </div>
          </div>
          <div className="mb-3">
            <label htmlFor="description" className="form-label">
              Description (optional)
            </label>
            <input type="text" className="form-control" id="description" />
          </div>

          <hr />

          <div className="form-check">
            <input
              className="form-check-input"
              type="radio"
              name="exampleRadios"
              id="exampleRadios1"
              value="option1"
              defaultChecked
            />
            <label className="form-check-label" htmlFor="exampleRadios1">
              Public
            </label>
          </div>
          <div className="form-check">
            <input
              className="form-check-input"
              type="radio"
              name="exampleRadios"
              id="exampleRadios2"
              value="option2"
            />
            <label className="form-check-label" htmlFor="exampleRadios2">
              Private
            </label>
          </div>

          <hr />

          <button type="submit" className="btn btn-success">
            Create Project
          </button>
        </form>
      </div>
    </>
  )
}
