import { useRouter } from "next/router"
import Head from "next/head"
import Link from "next/link"

import { Formik, Form, Field } from "formik"
import { NamespaceNameCreationSchema } from "@/lib/yup-schemas"

import axios from "axios"

export default function Home() {
  const router = useRouter()

  return (
    <>
      <Head>
        <title>Create namespace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-100">
        <div className="relative flex">
          {/* Content */}
          <div className="w-full">
            <div className="min-h-screen h-full flex flex-col after:flex-1">
              <div className="flex-1">
                {/* Header */}
                <div className="flex items-center justify-end h-16 px-4 sm:px-6 lg:px-8">
                  <div className="text-sm">
                    Have an account?{" "}
                    <Link
                      className="font-medium text-indigo-500 hover:text-indigo-600"
                      href={"/"}
                    >
                      Sign In
                    </Link>
                  </div>
                </div>

                {/* Progress bar */}
                <div className="px-4 pt-12 pb-8">
                  <div className="max-w-md mx-auto w-full">
                    <div className="relative">
                      <div
                        className="absolute left-0 top-1/2 -mt-px w-full h-0.5 bg-slate-200"
                        aria-hidden="true"
                      ></div>
                      <ul className="relative flex justify-between w-full">
                        <li>
                          <div className="flex items-center justify-center w-6 h-6 rounded-full text-xs font-semibold bg-indigo-500 text-white">
                            1
                          </div>
                        </li>
                        <li>
                          <div className="flex items-center justify-center w-6 h-6 rounded-full text-xs font-semibold bg-indigo-500 text-white">
                            2
                          </div>
                        </li>
                        <li>
                          <div className="flex items-center justify-center w-6 h-6 rounded-full text-xs font-semibold bg-slate-300 text-slate-500">
                            3
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>

              <div className="px-4 py-8">
                <div className="max-w-md mx-auto">
                  <h1 className="text-3xl text-slate-800 font-bold mb-9 text-center">
                    Finalize Profile
                  </h1>

                  <Formik
                    initialValues={{
                      name: ""
                    }}
                    validationSchema={NamespaceNameCreationSchema}
                    validateOnChange={false}
                    validateOnBlur={false}
                    onSubmit={(values, { setSubmitting, setFieldError }) => {
                      axios
                        .post("/api/user", {
                          name: values.name
                        })
                        .then((response) => {
                          console.log("RESPONSE:", response)
                          // router.push(`/${values.name}`)
                        })
                        .catch((error) => {
                          console.log("ERROR:", error.response.data)
                          console.log("ERROR:", error)
                        })
                        .finally(() => {
                          setSubmitting(false)
                        })
                    }}
                  >
                    {({ errors, isSubmitting, values, setFieldError }) => (
                      <Form onChange={() => setFieldError("name", false)}>
                        {errors.name && (
                          <div className="py-3">
                            <div className="flex w-full px-4 py-2 rounded-sm text-sm border bg-rose-100 border-rose-200 text-rose-600">
                              <div>You must enter a valid username!</div>
                            </div>
                          </div>
                        )}

                        <div>
                          <label className="block text-sm font-medium mb-1">
                            Username
                            <span className="text-rose-500">*</span>
                          </label>
                          <Field
                            className="form-input w-full"
                            type="text"
                            name="name"
                          />
                        </div>
                        <div className="text-sm pt-4 mb-8">
                          <p>
                            This will be the name of your account on Issue
                            Tracker.
                          </p>
                          <p>Your URL will be: </p>
                        </div>

                        <div className="flex items-center justify-between">
                          <Link
                            className="text-sm underline hover:no-underline"
                            href={"/"}
                          >
                            &lt;- Exit
                          </Link>

                          <div className="mt-3">
                            <button
                              className="btn bg-indigo-500 hover:bg-indigo-600 text-white ml-auto"
                              type="submit"
                              disabled={isSubmitting}
                            >
                              Finish Registration
                            </button>
                          </div>
                        </div>
                      </Form>
                    )}
                  </Formik>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
